# -*- coding: utf-8 -*-
"""b812113005 new code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kowwJlhjbeyd6_PzbKunaHzBppmbJGvi
"""

import argparse, pandas as pd, numpy as np
from sklearn.model_selection import KFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
from scipy.stats import pearsonr
import random

# 設定隨機種子，確保結果可重現
def set_seed(seed=42):
    np.random.seed(seed); random.seed(seed)

# 自定義皮爾森相關係數計算函式
def pearson(y_true, y_pred):
    # 若樣本值皆相同（無變化量），返回0避免nan
    if len(np.unique(y_true)) < 2 or len(np.unique(y_pred)) < 2:
        return 0.0
    # pearsonr 回傳物件的 statistic 屬性即為相關係數
    return pearsonr(y_true, y_pred).statistic

# 主訓練與驗證流程
def train_eval(train_path, dev_path=None, out_pred_path=None):
    set_seed(42)
    df_tr = pd.read_csv(train_path)  # 讀取訓練資料
    text = df_tr["text"].astype(str).values  # 文字欄轉字串
    y_v = df_tr["valence"].values            # 標籤：情緒價值
    y_a = df_tr["arousal"].values            # 標籤：喚起強度

    # 建立兩個模型管線：TF-IDF 向量化 + 岭回歸
    model_v = make_pipeline(
        TfidfVectorizer(ngram_range=(1,2), min_df=2, max_features=200000),
        Ridge(alpha=2.0, random_state=42)
    )
    model_a = make_pipeline(
        TfidfVectorizer(ngram_range=(1,2), min_df=2, max_features=200000),
        Ridge(alpha=2.0, random_state=42)
    )

    # 五折交叉驗證
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    preds_v = np.zeros(len(df_tr))
    preds_a = np.zeros(len(df_tr))
    for tr_idx, va_idx in kf.split(text):
        # 用訓練折訓練模型
        model_v.fit(text[tr_idx], y_v[tr_idx])
        model_a.fit(text[tr_idx], y_a[tr_idx])
        # 用驗證折預測並儲存結果
        preds_v[va_idx] = model_v.predict(text[va_idx])
        preds_a[va_idx] = model_a.predict(text[va_idx])

    # 計算交叉驗證平均表現
    print("[Train-CV] Valence  Pearson:", round(pearson(y_v, preds_v), 4),
          " MSE:", round(mean_squared_error(y_v, preds_v), 4))
    print("[Train-CV] Arousal  Pearson:", round(pearson(y_a, preds_a), 4),
          " MSE:", round(mean_squared_error(y_a, preds_a), 4))

    # 用全部資料重訓模型，準備預測dev/test
    model_v.fit(text, y_v)
    model_a.fit(text, y_a)

    # 若提供開發或測試集路徑
    if dev_path:
        df_dev = pd.read_csv(dev_path)
        x_dev = df_dev["text"].astype(str).values
        pv = model_v.predict(x_dev)  # 預測 valence
        pa = model_a.predict(x_dev)  # 預測 arousal

        # 若 dev 檔案內有真實標籤，評估性能
        if "valence" in df_dev and "arousal" in df_dev:
            print("[Dev] Valence   Pearson:", round(pearson(df_dev["valence"].values, pv), 4),
                  " MSE:", round(mean_squared_error(df_dev["valence"].values, pv), 4))
            print("[Dev] Arousal   Pearson:", round(pearson(df_dev["arousal"].values, pa), 4),
                  " MSE:", round(mean_squared_error(df_dev["arousal"].values, pa), 4))

        # 若指定輸出路徑，儲存預測結果
        if out_pred_path:
            out = df_dev[["id"]].copy()
            out["valence"] = pv
            out["arousal"] = pa
            out.to_csv(out_pred_path, index=False)
            print(f"[Saved] {out_pred_path}")

# 命令列介面入口
if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--train", required=True, help="path to train.csv")         # 訓練資料路徑
    ap.add_argument("--dev", required=False, help="path to dev.csv (labels optional)")  # 驗證資料路徑
    ap.add_argument("--out", required=False, help="path to save predictions on dev/test") # 輸出結果路徑
    args = ap.parse_args()
    # 執行訓練與預測
    train_eval(args.train, args.dev, args.out)

"""huggingface"""